object_estimation_node:
  ros__parameters:
    # Subscribers
    input_rgbd_image_topic: /camera/camera/rgbd

    # Publishers
    output_result_image_topic: /object_estimation/result_image
    output_ball_velocity_topic: /object_estimation/ball_velocity

    # Parameters
    yolo_model_path: /home/user/RoboBounce/models/yolo.pt
    filter_mode: one_euro  # kalman, one_euro, raw