object_estimation_node:
  ros__parameters:
    # Subscribers
    input_rgbd_image_topic: /camera/camera/rgbd

    # Publishers
    output_result_image_topic: /object_estimation/result_image

    # Parameters
    yolo_model_path: /home/user/RoboBounce/models/yolo.pt