object_estimation_node:
  ros__parameters:
    # Subscribers
    input_rgb_image_topic: /video_player/rgb_image

    # Publishers
    output_result_image_topic: /object_estimation/result_image

    # Parameters
    yolo_model_path: /home/user/RoboBounce/models/yolo.pt